ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080

tasks:
  weather:
    delay: 2000
    period: 600000

rest:
  client:
    base_url: "https://api.tomorrow.io/v4/timelines"
    api_key: "aJ89wn50v2Thr3djeqmh6vstzsmn899N"
    timeout: 5000
    retries: 3
    query_params:
      - name: "fields"
        value: "temperature,precipitationIntensity,windSpeed"
      - name: "timesteps"
        value: "current"
      - name: "units"
        value: "metric"

redis:
  server:
    url: "redis://localhost:6379"