ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8080

scheduled:
  task:
    interval: 2000
    delay: 2000

rest:
  client:
    base_url: "https://api.tomorrow.io/v4/timelines"
    api_key: "aJ89wn50v2Thr3djeqmh6vstzsmn899N"
    timeout: 5000
    retries: 3
